server_name: "qrtrust-local-nats"
port: 4222
http_port: 8222

jetstream {
  store_dir: "/data/jetstream"
}

authorization {
  timeout: 2
  users: [
    {
      user: "qrtrust_outbox_worker"
      password: "qrtrust_outbox_worker_dev"
      permissions: {
        publish: {
          allow: ["$JS.API.>", "qrtrust.>"]
        }
        subscribe: {
          allow: ["_INBOX.>"]
        }
      }
    }
    {
      user: "qrtrust_governance_subscriber"
      password: "qrtrust_governance_subscriber_dev"
      permissions: {
        publish: {
          allow: [
            "$JS.API.INFO",
            "$JS.API.CONSUMER.CREATE.QRTRUST_GOVERNANCE.*.>",
            "$JS.API.CONSUMER.DURABLE.CREATE.QRTRUST_GOVERNANCE.*",
            "$JS.API.CONSUMER.INFO.QRTRUST_GOVERNANCE.*",
            "$JS.API.CONSUMER.MSG.NEXT.QRTRUST_GOVERNANCE.*",
            "$JS.API.CONSUMER.DELETE.QRTRUST_GOVERNANCE.*",
            "$JS.ACK.QRTRUST_GOVERNANCE.>"
          ]
        }
        subscribe: {
          allow: [
            "_INBOX.>",
            "qrtrust.*.root.>",
            "qrtrust.*.authority.>",
            "qrtrust.*.issuer.>",
            "qrtrust.*.destination.>",
            "qrtrust.*.certificate.>"
          ]
        }
      }
    }
    {
      user: "qrtrust_runtime_subscriber"
      password: "qrtrust_runtime_subscriber_dev"
      permissions: {
        publish: {
          allow: [
            "$JS.API.INFO",
            "$JS.API.CONSUMER.CREATE.QRTRUST_RUNTIME.*.>",
            "$JS.API.CONSUMER.DURABLE.CREATE.QRTRUST_RUNTIME.*",
            "$JS.API.CONSUMER.INFO.QRTRUST_RUNTIME.*",
            "$JS.API.CONSUMER.MSG.NEXT.QRTRUST_RUNTIME.*",
            "$JS.API.CONSUMER.DELETE.QRTRUST_RUNTIME.*",
            "$JS.ACK.QRTRUST_RUNTIME.>"
          ]
        }
        subscribe: {
          allow: ["_INBOX.>", "qrtrust.*.runtime.>", "qrtrust.*.verifier.>"]
        }
      }
    }
    {
      user: "qrtrust_scanner_audit_subscriber"
      password: "qrtrust_scanner_audit_subscriber_dev"
      permissions: {
        publish: {
          allow: [
            "$JS.API.INFO",
            "$JS.API.CONSUMER.CREATE.QRTRUST_SCANNER_AUDIT.*.>",
            "$JS.API.CONSUMER.DURABLE.CREATE.QRTRUST_SCANNER_AUDIT.*",
            "$JS.API.CONSUMER.INFO.QRTRUST_SCANNER_AUDIT.*",
            "$JS.API.CONSUMER.MSG.NEXT.QRTRUST_SCANNER_AUDIT.*",
            "$JS.API.CONSUMER.DELETE.QRTRUST_SCANNER_AUDIT.*",
            "$JS.ACK.QRTRUST_SCANNER_AUDIT.>"
          ]
        }
        subscribe: {
          allow: ["_INBOX.>", "qrtrust.*.scanner.>"]
        }
      }
    }
  ]
}
