#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUTPUT_FILE="${IOS_PROVIDER_CONFIG_FILE:-$ROOT_DIR/ios/VerifierLabApp/LocalProvider.xcconfig}"

detect_local_hostname() {
  if command -v scutil >/dev/null 2>&1; then
    scutil --get LocalHostName 2>/dev/null | awk 'NF { sub(/\.local$/, "", $0); print $0 ".local"; exit }'
    return 0
  fi

  hostname -s 2>/dev/null | awk 'NF { sub(/\.local$/, "", $0); print $0 ".local"; exit }'
}

detect_lan_ip() {
  if command -v ipconfig >/dev/null 2>&1; then
    for iface in en0 en1; do
      ipconfig getifaddr "$iface" 2>/dev/null && return 0
    done
  fi

  hostname -I 2>/dev/null | awk '{ print $1; exit }'
}

xcconfig_https_url() {
  # Xcode xcconfig treats // as a comment marker, so keep the scheme split.
  printf 'https:/$()/%s:8443' "$1"
}

display_https_url() {
  printf 'https://%s:8443' "$1"
}

local_hostname="$(detect_local_hostname || true)"
lan_ip="$(detect_lan_ip || true)"
candidates=""
display_candidates=""

append_candidate() {
  host="$1"
  [ -n "$host" ] || return 0

  candidate="$(xcconfig_https_url "$host")"
  display_candidate="$(display_https_url "$host")"

  case ",$candidates," in
    *",$candidate,"*) return 0 ;;
  esac

  if [ -z "$candidates" ]; then
    candidates="$candidate"
    display_candidates="$display_candidate"
  else
    candidates="$candidates,$candidate"
    display_candidates="$display_candidates
$display_candidate"
  fi
}

append_candidate "$local_hostname"
append_candidate "$lan_ip"

if [ -z "$candidates" ]; then
  echo "Could not detect a Bonjour hostname or LAN IP for the iOS provider profile." >&2
  exit 1
fi

mkdir -p "$(dirname -- "$OUTPUT_FILE")"
cat > "$OUTPUT_FILE" <<EOF
// Generated by scripts/write_ios_local_provider_config.sh.
// Local only. Do not commit.
QRTRUST_VERIFIER_BASE_URLS = $candidates
EOF

echo "iOS local provider config written: $OUTPUT_FILE"
echo "Provider candidates embedded into the next iOS build:"
printf '%s\n' "$display_candidates" | sed 's/^/  - /'
